// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDo6N_t8B_QIlGZLvr2IQYXA7EaRNHjqec',
//     appId: '1:171119924602:web:ebe8a3631fd7fdd4e272c3',
//     messagingSenderId: '171119924602',
//     projectId: 'dialogflowfarmacia',
//     authDomain: 'dialogflowfarmacia.firebaseapp.com',
//     storageBucket: 'dialogflowfarmacia.appspot.com',
//     measurementId: 'G-S6DV6WPWCK',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAGUTVzNZroABSunKYi-Jkeekvr7xZFGGo',
//     appId: '1:171119924602:android:66972f2cb3403958e272c3',
//     messagingSenderId: '171119924602',
//     projectId: 'dialogflowfarmacia',
//     storageBucket: 'dialogflowfarmacia.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAnXOMRsDD3j9y0X2EQlGAO52DcBESq7pE',
//     appId: '1:171119924602:ios:aea39dbab95463c5e272c3',
//     messagingSenderId: '171119924602',
//     projectId: 'dialogflowfarmacia',
//     storageBucket: 'dialogflowfarmacia.appspot.com',
//     iosBundleId: 'com.example.farmacia',
//   );
// }
